[build-system]
requires = ["setuptools", "wheel", "matplotlib", "numpy", "pandas", "pytest", "pytest-cov"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 120
target-version = ['py39', 'py310']
